### PR TITLE
Add slug and collection_slug columns to collection_chapter

### PR DESCRIPTION
**Pull request by loafofpiecrust**
Add these two generated columns to collection_chapter to make certain queries more convenient. Also, add a constraint that requires chapter slugs be unique within each collection.

### CODE REVIEW

**Review by chanmioh — APPROVED** [review]
I think this looks good! I guess the only question I have is what we'd need the `chapter_path` for, since we're using a chapter's `collection_slug` and `slug` to reference a chapter.

**Comment by loafofpiecrust** [comment]
The `chapter_path` will define the hierarchy, which we'll use for table of contents and breadcrumbs

**Comment by nole2701** [comment]
> The `chapter_path` will define the hierarchy, which we'll use for table of contents and breadcrumbs

Would keeping chapter_path also help to keep old usages working without needing to go back and change them all?

**Comment by loafofpiecrust** [comment]
The reason to have this setup instead of directly storing `slug` and a `parent_id` is that with an ltree we don't have to do a recursive query to figure out the full path of a chapter, which will be a common operation.

**Comment by loafofpiecrust** [comment]
> > The `chapter_path` will define the hierarchy, which we'll use for table of contents and breadcrumbs
> 
> Would keeping chapter_path also help to keep old usages working without needing to go back and change them all?

Yes I suppose, but the alternative of getting rid of `chapter_path` would require a restructuring of the table in general. These new fields are generated from `chapter_path`, we can treat them like functions. You can't change their value directly, you can only observe the value after changing `chapter_path`.

**Review by nole2701 — APPROVED** [review]
It looks good. With the additions relating to chapter_path and slugs if they're derived from chapter_path then it should be fine.

**Pull request merged**
